
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { uploadMultipleImages } from '@/utils/imageUtils';
import { normalizeUrl, isValidUrl } from '@/utils/urlUtils';
import { Form } from '@/components/ui/form';
import RaffleFormFields from './RaffleFormFields';
import ConfirmationDialog from './ConfirmationDialog';

// Custom URL validation that normalizes URLs and validates them
const urlSchema = z.string()
  .min(1, 'URL is required')
  .transform(normalizeUrl)
  .refine(isValidUrl, 'Must be a valid URL');

const raffleFormSchema = z.object({
  title: z.string().min(5, 'Title must be at least 5 characters'),
  batchNumber: z.string().optional(),
  description: z.string().min(20, 'Description must be at least 20 characters'),
  grandPrize: z.string().min(3, 'Grand prize is required'),
  grandPrizeValue: z.number().min(1, 'Prize value must be greater than 0'),
  convertibleToCash: z.boolean().default(false),
  category: z.enum(['Cars', 'Motorcycle', 'Gadgets', 'Cash']),
  costPerSlot: z.number().min(1, 'Cost per slot must be greater than 0'),
  totalSlots: z.number().min(1, 'Total slots must be greater than 0'),
  isDrawDateTBD: z.boolean().default(false),
  drawDate: z.string().optional(),
  organizationName: z.string().min(2, 'Organization name is required'),
  facebookPageUrl: urlSchema,
  raffleLink: urlSchema,
  buyingSlotsUrl: urlSchema,
  grandPrizeImages: z.any().optional(),
  consolationPrizes: z.array(z.object({
    title: z.string().min(1, 'Prize title is required'),
    value: z.number().min(0, 'Prize value must be 0 or greater'),
    isCash: z.boolean().default(false),
    images: z.any().optional()
  })).optional(),
  bundlePricing: z.array(z.object({
    slots: z.number().min(1, 'Slots must be greater than 0'),
    price: z.number().min(1, 'Price must be greater than 0')
  })).optional()
}).refine((data) => {
  // If draw date is not TBD, then drawDate is required
  if (!data.isDrawDateTBD && !data.drawDate) {
    return false;
  }
  return true;
}, {
  message: "Draw date is required when not marked as TBD",
  path: ["drawDate"]
});

export type RaffleFormData = z.infer<typeof raffleFormSchema>;

const RaffleFormHandler = () => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submissionStep, setSubmissionStep] = useState<string>('');
  const [showConfirmation, setShowConfirmation] = useState(false);
  const { toast } = useToast();

  const form = useForm<RaffleFormData>({
    resolver: zodResolver(raffleFormSchema),
    defaultValues: {
      convertibleToCash: false,
      isDrawDateTBD: false,
      consolationPrizes: [],
      bundlePricing: []
    }
  });

  const onSubmit = async (data: RaffleFormData) => {
    try {
      setIsSubmitting(true);
      setSubmissionStep('Starting submission...');
      console.log('🚀 Starting raffle submission');

      // Upload grand prize images
      let grandPrizeImageUrls: string[] = [];
      if (data.grandPrizeImages && data.grandPrizeImages.length > 0) {
        setSubmissionStep('Uploading grand prize images...');
        const uploadResults = await uploadMultipleImages(
          data.grandPrizeImages,
          'raffle-images',
          'grand-prizes'
        );
        grandPrizeImageUrls = uploadResults.map(result => result.url);
        console.log('✅ Grand prize images uploaded:', grandPrizeImageUrls);
      }

      setSubmissionStep('Creating raffle record...');
      
      // Prepare raffle data - set draw_date to null if TBD is selected
      const raffleData = {
        title: data.title,
        batch_number: data.batchNumber || null,
        description: data.description,
        slug: '', // Will be auto-generated by trigger
        grand_prize: data.grandPrize,
        grand_prize_value: data.grandPrizeValue,
        grand_prize_images: grandPrizeImageUrls,
        convertible_to_cash: data.convertibleToCash,
        category: data.category,
        cost_per_slot: data.costPerSlot,
        total_slots: data.totalSlots,
        draw_date: data.isDrawDateTBD ? null : data.drawDate,
        organization_name: data.organizationName,
        facebook_page_url: data.facebookPageUrl,
        raffle_link: data.raffleLink,
        buying_slots_url: data.buyingSlotsUrl,
        approved: false
      };

      const { data: insertedRaffle, error: raffleError } = await supabase
        .from('raffles')
        .insert(raffleData)
        .select()
        .single();

      if (raffleError) {
        throw new Error(`Database error: ${raffleError.message}`);
      }

      console.log('✅ Raffle inserted successfully:', insertedRaffle);
      const raffleId = insertedRaffle.id;

      // Insert consolation prizes if any
      if (data.consolationPrizes && data.consolationPrizes.length > 0) {
        setSubmissionStep('Processing consolation prizes...');
        
        const consolationPrizesData = await Promise.all(
          data.consolationPrizes.map(async (prize) => {
            let prizeImageUrls: string[] = [];
            if (prize.images && prize.images.length > 0 && !prize.isCash) {
              const uploadResults = await uploadMultipleImages(
                prize.images,
                'prize-images',
                'consolation-prizes'
              );
              prizeImageUrls = uploadResults.map(result => result.url);
            }

            return {
              raffle_id: raffleId,
              title: prize.title,
              value: prize.value,
              is_cash: prize.isCash,
              images: prizeImageUrls
            };
          })
        );

        const { error: consolationError } = await supabase
          .from('consolation_prizes')
          .insert(consolationPrizesData);

        if (consolationError) {
          throw new Error(`Consolation prizes error: ${consolationError.message}`);
        }
        console.log('✅ Consolation prizes inserted');
      }

      // Insert bundle pricing if any
      if (data.bundlePricing && data.bundlePricing.length > 0) {
        setSubmissionStep('Processing bundle pricing...');
        
        const bundlePricingData = data.bundlePricing.map(bundle => ({
          raffle_id: raffleId,
          slots: bundle.slots,
          price: bundle.price
        }));

        const { error: bundleError } = await supabase
          .from('bundle_pricing')
          .insert(bundlePricingData);

        if (bundleError) {
          throw new Error(`Bundle pricing error: ${bundleError.message}`);
        }
        console.log('✅ Bundle pricing inserted');
      }

      setSubmissionStep('Complete!');
      console.log('🎉 Raffle submission completed successfully!');
      
      // Show confirmation dialog instead of toast
      setShowConfirmation(true);

      // Reset form
      form.reset();

    } catch (error) {
      console.error('💥 Submission error:', error);
      
      let errorMessage = "Something went wrong. Please try again.";
      
      if (error instanceof Error) {
        if (error.message.includes('violates row-level security')) {
          errorMessage = "Permission denied. Please contact support.";
        } else if (error.message.includes('duplicate key')) {
          errorMessage = "A raffle with similar details already exists.";
        } else {
          errorMessage = error.message;
        }
      }
      
      toast({
        title: "❌ Submission Failed",
        description: errorMessage,
        variant: "destructive",
        duration: 8000
      });
    } finally {
      setIsSubmitting(false);
      setSubmissionStep('');
    }
  };

  const handleSubmit = () => {
    form.handleSubmit(onSubmit)();
  };

  return (
    <>
      <div className="max-w-4xl mx-auto p-6">
        <Form {...form}>
          <form className="space-y-8">
            <RaffleFormFields 
              form={form} 
              isSubmitting={isSubmitting}
              submissionStep={submissionStep}
              onSubmit={handleSubmit}
            />
          </form>
        </Form>
      </div>

      <ConfirmationDialog 
        open={showConfirmation}
        onOpenChange={setShowConfirmation}
      />
    </>
  );
};

export default RaffleFormHandler;
